/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ekf_predict_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {15, 15, 1};

/* predict_function:(X[15],U[6],W[6],dt,P[15x15],Q[6])->(X_pred[15],P_pred[15x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a02=arg[3]? arg[3][0] : 0;
  a03=(a01*a02);
  a00=(a00+a03);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a03=arg[0]? arg[0][4] : 0;
  a04=(a03*a02);
  a00=(a00+a04);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a04*a02);
  a00=(a00+a05);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  a00=(a00*a02);
  a01=(a01+a00);
  if (res[0]!=0) res[0][3]=a01;
  a01=arg[1]? arg[1][1] : 0;
  a01=(a01*a02);
  a03=(a03+a01);
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[1]? arg[1][2] : 0;
  a01=9.8100000000000005e+00;
  a03=(a03-a01);
  a03=(a03*a02);
  a04=(a04+a03);
  if (res[0]!=0) res[0][5]=a04;
  a04=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a04;
  a04=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a04;
  a04=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a04;
  a04=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a04;
  a04=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a04;
  a04=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a04;
  a04=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a04;
  a04=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a04;
  a04=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a04;
  a04=arg[4]? arg[4][0] : 0;
  a03=arg[4]? arg[4][3] : 0;
  a01=(a02*a03);
  a04=(a04+a01);
  a01=arg[4]? arg[4][45] : 0;
  a00=arg[4]? arg[4][48] : 0;
  a05=(a02*a00);
  a01=(a01+a05);
  a05=(a01*a02);
  a04=(a04+a05);
  if (res[1]!=0) res[1][0]=a04;
  a04=arg[4]? arg[4][1] : 0;
  a05=arg[4]? arg[4][4] : 0;
  a06=(a02*a05);
  a04=(a04+a06);
  a06=arg[4]? arg[4][46] : 0;
  a07=arg[4]? arg[4][49] : 0;
  a08=(a02*a07);
  a06=(a06+a08);
  a08=(a06*a02);
  a04=(a04+a08);
  if (res[1]!=0) res[1][1]=a04;
  a04=arg[4]? arg[4][2] : 0;
  a08=arg[4]? arg[4][5] : 0;
  a09=(a02*a08);
  a04=(a04+a09);
  a09=arg[4]? arg[4][47] : 0;
  a10=arg[4]? arg[4][50] : 0;
  a11=(a02*a10);
  a09=(a09+a11);
  a11=(a09*a02);
  a04=(a04+a11);
  if (res[1]!=0) res[1][2]=a04;
  a04=(a00*a02);
  a03=(a03+a04);
  if (res[1]!=0) res[1][3]=a03;
  a03=(a07*a02);
  a05=(a05+a03);
  if (res[1]!=0) res[1][4]=a05;
  a05=(a10*a02);
  a08=(a08+a05);
  if (res[1]!=0) res[1][5]=a08;
  a08=arg[4]? arg[4][6] : 0;
  a05=arg[4]? arg[4][51] : 0;
  a03=(a05*a02);
  a08=(a08+a03);
  if (res[1]!=0) res[1][6]=a08;
  a08=arg[4]? arg[4][7] : 0;
  a03=arg[4]? arg[4][52] : 0;
  a04=(a03*a02);
  a08=(a08+a04);
  if (res[1]!=0) res[1][7]=a08;
  a08=arg[4]? arg[4][8] : 0;
  a04=arg[4]? arg[4][53] : 0;
  a11=(a04*a02);
  a08=(a08+a11);
  if (res[1]!=0) res[1][8]=a08;
  a08=arg[4]? arg[4][9] : 0;
  a11=arg[4]? arg[4][54] : 0;
  a12=(a11*a02);
  a08=(a08+a12);
  if (res[1]!=0) res[1][9]=a08;
  a08=arg[4]? arg[4][10] : 0;
  a12=arg[4]? arg[4][55] : 0;
  a13=(a12*a02);
  a08=(a08+a13);
  if (res[1]!=0) res[1][10]=a08;
  a08=arg[4]? arg[4][11] : 0;
  a13=arg[4]? arg[4][56] : 0;
  a14=(a13*a02);
  a08=(a08+a14);
  if (res[1]!=0) res[1][11]=a08;
  a08=arg[4]? arg[4][12] : 0;
  a14=arg[4]? arg[4][57] : 0;
  a15=(a14*a02);
  a08=(a08+a15);
  if (res[1]!=0) res[1][12]=a08;
  a08=arg[4]? arg[4][13] : 0;
  a15=arg[4]? arg[4][58] : 0;
  a16=(a15*a02);
  a08=(a08+a16);
  if (res[1]!=0) res[1][13]=a08;
  a08=arg[4]? arg[4][14] : 0;
  a16=arg[4]? arg[4][59] : 0;
  a17=(a16*a02);
  a08=(a08+a17);
  if (res[1]!=0) res[1][14]=a08;
  a08=arg[4]? arg[4][15] : 0;
  a17=arg[4]? arg[4][18] : 0;
  a18=(a02*a17);
  a08=(a08+a18);
  a18=arg[4]? arg[4][60] : 0;
  a19=arg[4]? arg[4][63] : 0;
  a20=(a02*a19);
  a18=(a18+a20);
  a20=(a18*a02);
  a08=(a08+a20);
  if (res[1]!=0) res[1][15]=a08;
  a08=arg[4]? arg[4][16] : 0;
  a20=arg[4]? arg[4][19] : 0;
  a21=(a02*a20);
  a08=(a08+a21);
  a21=arg[4]? arg[4][61] : 0;
  a22=arg[4]? arg[4][64] : 0;
  a23=(a02*a22);
  a21=(a21+a23);
  a23=(a21*a02);
  a08=(a08+a23);
  if (res[1]!=0) res[1][16]=a08;
  a08=arg[4]? arg[4][17] : 0;
  a23=arg[4]? arg[4][20] : 0;
  a24=(a02*a23);
  a08=(a08+a24);
  a24=arg[4]? arg[4][62] : 0;
  a25=arg[4]? arg[4][65] : 0;
  a26=(a02*a25);
  a24=(a24+a26);
  a26=(a24*a02);
  a08=(a08+a26);
  if (res[1]!=0) res[1][17]=a08;
  a08=(a19*a02);
  a17=(a17+a08);
  if (res[1]!=0) res[1][18]=a17;
  a17=(a22*a02);
  a20=(a20+a17);
  if (res[1]!=0) res[1][19]=a20;
  a20=(a25*a02);
  a23=(a23+a20);
  if (res[1]!=0) res[1][20]=a23;
  a23=arg[4]? arg[4][21] : 0;
  a20=arg[4]? arg[4][66] : 0;
  a17=(a20*a02);
  a23=(a23+a17);
  if (res[1]!=0) res[1][21]=a23;
  a23=arg[4]? arg[4][22] : 0;
  a17=arg[4]? arg[4][67] : 0;
  a08=(a17*a02);
  a23=(a23+a08);
  if (res[1]!=0) res[1][22]=a23;
  a23=arg[4]? arg[4][23] : 0;
  a08=arg[4]? arg[4][68] : 0;
  a26=(a08*a02);
  a23=(a23+a26);
  if (res[1]!=0) res[1][23]=a23;
  a23=arg[4]? arg[4][24] : 0;
  a26=arg[4]? arg[4][69] : 0;
  a27=(a26*a02);
  a23=(a23+a27);
  if (res[1]!=0) res[1][24]=a23;
  a23=arg[4]? arg[4][25] : 0;
  a27=arg[4]? arg[4][70] : 0;
  a28=(a27*a02);
  a23=(a23+a28);
  if (res[1]!=0) res[1][25]=a23;
  a23=arg[4]? arg[4][26] : 0;
  a28=arg[4]? arg[4][71] : 0;
  a29=(a28*a02);
  a23=(a23+a29);
  if (res[1]!=0) res[1][26]=a23;
  a23=arg[4]? arg[4][27] : 0;
  a29=arg[4]? arg[4][72] : 0;
  a30=(a29*a02);
  a23=(a23+a30);
  if (res[1]!=0) res[1][27]=a23;
  a23=arg[4]? arg[4][28] : 0;
  a30=arg[4]? arg[4][73] : 0;
  a31=(a30*a02);
  a23=(a23+a31);
  if (res[1]!=0) res[1][28]=a23;
  a23=arg[4]? arg[4][29] : 0;
  a31=arg[4]? arg[4][74] : 0;
  a32=(a31*a02);
  a23=(a23+a32);
  if (res[1]!=0) res[1][29]=a23;
  a23=arg[4]? arg[4][30] : 0;
  a32=arg[4]? arg[4][33] : 0;
  a33=(a02*a32);
  a23=(a23+a33);
  a33=arg[4]? arg[4][75] : 0;
  a34=arg[4]? arg[4][78] : 0;
  a35=(a02*a34);
  a33=(a33+a35);
  a35=(a33*a02);
  a23=(a23+a35);
  if (res[1]!=0) res[1][30]=a23;
  a23=arg[4]? arg[4][31] : 0;
  a35=arg[4]? arg[4][34] : 0;
  a36=(a02*a35);
  a23=(a23+a36);
  a36=arg[4]? arg[4][76] : 0;
  a37=arg[4]? arg[4][79] : 0;
  a38=(a02*a37);
  a36=(a36+a38);
  a38=(a36*a02);
  a23=(a23+a38);
  if (res[1]!=0) res[1][31]=a23;
  a23=arg[4]? arg[4][32] : 0;
  a38=arg[4]? arg[4][35] : 0;
  a39=(a02*a38);
  a23=(a23+a39);
  a39=arg[4]? arg[4][77] : 0;
  a40=arg[4]? arg[4][80] : 0;
  a41=(a02*a40);
  a39=(a39+a41);
  a41=(a39*a02);
  a23=(a23+a41);
  if (res[1]!=0) res[1][32]=a23;
  a23=(a34*a02);
  a32=(a32+a23);
  if (res[1]!=0) res[1][33]=a32;
  a32=(a37*a02);
  a35=(a35+a32);
  if (res[1]!=0) res[1][34]=a35;
  a35=(a40*a02);
  a38=(a38+a35);
  if (res[1]!=0) res[1][35]=a38;
  a38=arg[4]? arg[4][36] : 0;
  a35=arg[4]? arg[4][81] : 0;
  a32=(a35*a02);
  a38=(a38+a32);
  if (res[1]!=0) res[1][36]=a38;
  a38=arg[4]? arg[4][37] : 0;
  a32=arg[4]? arg[4][82] : 0;
  a23=(a32*a02);
  a38=(a38+a23);
  if (res[1]!=0) res[1][37]=a38;
  a38=arg[4]? arg[4][38] : 0;
  a23=arg[4]? arg[4][83] : 0;
  a41=(a23*a02);
  a38=(a38+a41);
  if (res[1]!=0) res[1][38]=a38;
  a38=arg[4]? arg[4][39] : 0;
  a41=arg[4]? arg[4][84] : 0;
  a42=(a41*a02);
  a38=(a38+a42);
  if (res[1]!=0) res[1][39]=a38;
  a38=arg[4]? arg[4][40] : 0;
  a42=arg[4]? arg[4][85] : 0;
  a43=(a42*a02);
  a38=(a38+a43);
  if (res[1]!=0) res[1][40]=a38;
  a38=arg[4]? arg[4][41] : 0;
  a43=arg[4]? arg[4][86] : 0;
  a44=(a43*a02);
  a38=(a38+a44);
  if (res[1]!=0) res[1][41]=a38;
  a38=arg[4]? arg[4][42] : 0;
  a44=arg[4]? arg[4][87] : 0;
  a45=(a44*a02);
  a38=(a38+a45);
  if (res[1]!=0) res[1][42]=a38;
  a38=arg[4]? arg[4][43] : 0;
  a45=arg[4]? arg[4][88] : 0;
  a46=(a45*a02);
  a38=(a38+a46);
  if (res[1]!=0) res[1][43]=a38;
  a38=arg[4]? arg[4][44] : 0;
  a46=arg[4]? arg[4][89] : 0;
  a47=(a46*a02);
  a38=(a38+a47);
  if (res[1]!=0) res[1][44]=a38;
  if (res[1]!=0) res[1][45]=a01;
  if (res[1]!=0) res[1][46]=a06;
  if (res[1]!=0) res[1][47]=a09;
  a09=arg[5]? arg[5][0] : 0;
  a09=(a02*a09);
  a09=(a09*a02);
  a00=(a00+a09);
  if (res[1]!=0) res[1][48]=a00;
  if (res[1]!=0) res[1][49]=a07;
  if (res[1]!=0) res[1][50]=a10;
  if (res[1]!=0) res[1][51]=a05;
  if (res[1]!=0) res[1][52]=a03;
  if (res[1]!=0) res[1][53]=a04;
  if (res[1]!=0) res[1][54]=a11;
  if (res[1]!=0) res[1][55]=a12;
  if (res[1]!=0) res[1][56]=a13;
  if (res[1]!=0) res[1][57]=a14;
  if (res[1]!=0) res[1][58]=a15;
  if (res[1]!=0) res[1][59]=a16;
  if (res[1]!=0) res[1][60]=a18;
  if (res[1]!=0) res[1][61]=a21;
  if (res[1]!=0) res[1][62]=a24;
  if (res[1]!=0) res[1][63]=a19;
  a19=arg[5]? arg[5][1] : 0;
  a19=(a02*a19);
  a19=(a19*a02);
  a22=(a22+a19);
  if (res[1]!=0) res[1][64]=a22;
  if (res[1]!=0) res[1][65]=a25;
  if (res[1]!=0) res[1][66]=a20;
  if (res[1]!=0) res[1][67]=a17;
  if (res[1]!=0) res[1][68]=a08;
  if (res[1]!=0) res[1][69]=a26;
  if (res[1]!=0) res[1][70]=a27;
  if (res[1]!=0) res[1][71]=a28;
  if (res[1]!=0) res[1][72]=a29;
  if (res[1]!=0) res[1][73]=a30;
  if (res[1]!=0) res[1][74]=a31;
  if (res[1]!=0) res[1][75]=a33;
  if (res[1]!=0) res[1][76]=a36;
  if (res[1]!=0) res[1][77]=a39;
  if (res[1]!=0) res[1][78]=a34;
  if (res[1]!=0) res[1][79]=a37;
  a37=arg[5]? arg[5][2] : 0;
  a37=(a02*a37);
  a37=(a37*a02);
  a40=(a40+a37);
  if (res[1]!=0) res[1][80]=a40;
  if (res[1]!=0) res[1][81]=a35;
  if (res[1]!=0) res[1][82]=a32;
  if (res[1]!=0) res[1][83]=a23;
  if (res[1]!=0) res[1][84]=a41;
  if (res[1]!=0) res[1][85]=a42;
  if (res[1]!=0) res[1][86]=a43;
  if (res[1]!=0) res[1][87]=a44;
  if (res[1]!=0) res[1][88]=a45;
  if (res[1]!=0) res[1][89]=a46;
  a46=arg[4]? arg[4][90] : 0;
  a45=arg[4]? arg[4][93] : 0;
  a44=(a02*a45);
  a46=(a46+a44);
  if (res[1]!=0) res[1][90]=a46;
  a46=arg[4]? arg[4][91] : 0;
  a44=arg[4]? arg[4][94] : 0;
  a43=(a02*a44);
  a46=(a46+a43);
  if (res[1]!=0) res[1][91]=a46;
  a46=arg[4]? arg[4][92] : 0;
  a43=arg[4]? arg[4][95] : 0;
  a42=(a02*a43);
  a46=(a46+a42);
  if (res[1]!=0) res[1][92]=a46;
  if (res[1]!=0) res[1][93]=a45;
  if (res[1]!=0) res[1][94]=a44;
  if (res[1]!=0) res[1][95]=a43;
  a43=arg[4]? arg[4][96] : 0;
  if (res[1]!=0) res[1][96]=a43;
  a43=arg[4]? arg[4][97] : 0;
  if (res[1]!=0) res[1][97]=a43;
  a43=arg[4]? arg[4][98] : 0;
  if (res[1]!=0) res[1][98]=a43;
  a43=arg[4]? arg[4][99] : 0;
  if (res[1]!=0) res[1][99]=a43;
  a43=arg[4]? arg[4][100] : 0;
  if (res[1]!=0) res[1][100]=a43;
  a43=arg[4]? arg[4][101] : 0;
  if (res[1]!=0) res[1][101]=a43;
  a43=arg[4]? arg[4][102] : 0;
  if (res[1]!=0) res[1][102]=a43;
  a43=arg[4]? arg[4][103] : 0;
  if (res[1]!=0) res[1][103]=a43;
  a43=arg[4]? arg[4][104] : 0;
  if (res[1]!=0) res[1][104]=a43;
  a43=arg[4]? arg[4][105] : 0;
  a44=arg[4]? arg[4][108] : 0;
  a45=(a02*a44);
  a43=(a43+a45);
  if (res[1]!=0) res[1][105]=a43;
  a43=arg[4]? arg[4][106] : 0;
  a45=arg[4]? arg[4][109] : 0;
  a46=(a02*a45);
  a43=(a43+a46);
  if (res[1]!=0) res[1][106]=a43;
  a43=arg[4]? arg[4][107] : 0;
  a46=arg[4]? arg[4][110] : 0;
  a42=(a02*a46);
  a43=(a43+a42);
  if (res[1]!=0) res[1][107]=a43;
  if (res[1]!=0) res[1][108]=a44;
  if (res[1]!=0) res[1][109]=a45;
  if (res[1]!=0) res[1][110]=a46;
  a46=arg[4]? arg[4][111] : 0;
  if (res[1]!=0) res[1][111]=a46;
  a46=arg[4]? arg[4][112] : 0;
  if (res[1]!=0) res[1][112]=a46;
  a46=arg[4]? arg[4][113] : 0;
  if (res[1]!=0) res[1][113]=a46;
  a46=arg[4]? arg[4][114] : 0;
  if (res[1]!=0) res[1][114]=a46;
  a46=arg[4]? arg[4][115] : 0;
  if (res[1]!=0) res[1][115]=a46;
  a46=arg[4]? arg[4][116] : 0;
  if (res[1]!=0) res[1][116]=a46;
  a46=arg[4]? arg[4][117] : 0;
  if (res[1]!=0) res[1][117]=a46;
  a46=arg[4]? arg[4][118] : 0;
  if (res[1]!=0) res[1][118]=a46;
  a46=arg[4]? arg[4][119] : 0;
  if (res[1]!=0) res[1][119]=a46;
  a46=arg[4]? arg[4][120] : 0;
  a45=arg[4]? arg[4][123] : 0;
  a44=(a02*a45);
  a46=(a46+a44);
  if (res[1]!=0) res[1][120]=a46;
  a46=arg[4]? arg[4][121] : 0;
  a44=arg[4]? arg[4][124] : 0;
  a43=(a02*a44);
  a46=(a46+a43);
  if (res[1]!=0) res[1][121]=a46;
  a46=arg[4]? arg[4][122] : 0;
  a43=arg[4]? arg[4][125] : 0;
  a42=(a02*a43);
  a46=(a46+a42);
  if (res[1]!=0) res[1][122]=a46;
  if (res[1]!=0) res[1][123]=a45;
  if (res[1]!=0) res[1][124]=a44;
  if (res[1]!=0) res[1][125]=a43;
  a43=arg[4]? arg[4][126] : 0;
  if (res[1]!=0) res[1][126]=a43;
  a43=arg[4]? arg[4][127] : 0;
  if (res[1]!=0) res[1][127]=a43;
  a43=arg[4]? arg[4][128] : 0;
  if (res[1]!=0) res[1][128]=a43;
  a43=arg[4]? arg[4][129] : 0;
  if (res[1]!=0) res[1][129]=a43;
  a43=arg[4]? arg[4][130] : 0;
  if (res[1]!=0) res[1][130]=a43;
  a43=arg[4]? arg[4][131] : 0;
  if (res[1]!=0) res[1][131]=a43;
  a43=arg[4]? arg[4][132] : 0;
  if (res[1]!=0) res[1][132]=a43;
  a43=arg[4]? arg[4][133] : 0;
  if (res[1]!=0) res[1][133]=a43;
  a43=arg[4]? arg[4][134] : 0;
  if (res[1]!=0) res[1][134]=a43;
  a43=arg[4]? arg[4][135] : 0;
  a44=arg[4]? arg[4][138] : 0;
  a45=(a02*a44);
  a43=(a43+a45);
  if (res[1]!=0) res[1][135]=a43;
  a43=arg[4]? arg[4][136] : 0;
  a45=arg[4]? arg[4][139] : 0;
  a46=(a02*a45);
  a43=(a43+a46);
  if (res[1]!=0) res[1][136]=a43;
  a43=arg[4]? arg[4][137] : 0;
  a46=arg[4]? arg[4][140] : 0;
  a42=(a02*a46);
  a43=(a43+a42);
  if (res[1]!=0) res[1][137]=a43;
  if (res[1]!=0) res[1][138]=a44;
  if (res[1]!=0) res[1][139]=a45;
  if (res[1]!=0) res[1][140]=a46;
  a46=arg[4]? arg[4][141] : 0;
  if (res[1]!=0) res[1][141]=a46;
  a46=arg[4]? arg[4][142] : 0;
  if (res[1]!=0) res[1][142]=a46;
  a46=arg[4]? arg[4][143] : 0;
  if (res[1]!=0) res[1][143]=a46;
  a46=arg[4]? arg[4][144] : 0;
  if (res[1]!=0) res[1][144]=a46;
  a46=arg[4]? arg[4][145] : 0;
  if (res[1]!=0) res[1][145]=a46;
  a46=arg[4]? arg[4][146] : 0;
  if (res[1]!=0) res[1][146]=a46;
  a46=arg[4]? arg[4][147] : 0;
  if (res[1]!=0) res[1][147]=a46;
  a46=arg[4]? arg[4][148] : 0;
  if (res[1]!=0) res[1][148]=a46;
  a46=arg[4]? arg[4][149] : 0;
  if (res[1]!=0) res[1][149]=a46;
  a46=arg[4]? arg[4][150] : 0;
  a45=arg[4]? arg[4][153] : 0;
  a44=(a02*a45);
  a46=(a46+a44);
  if (res[1]!=0) res[1][150]=a46;
  a46=arg[4]? arg[4][151] : 0;
  a44=arg[4]? arg[4][154] : 0;
  a43=(a02*a44);
  a46=(a46+a43);
  if (res[1]!=0) res[1][151]=a46;
  a46=arg[4]? arg[4][152] : 0;
  a43=arg[4]? arg[4][155] : 0;
  a42=(a02*a43);
  a46=(a46+a42);
  if (res[1]!=0) res[1][152]=a46;
  if (res[1]!=0) res[1][153]=a45;
  if (res[1]!=0) res[1][154]=a44;
  if (res[1]!=0) res[1][155]=a43;
  a43=arg[4]? arg[4][156] : 0;
  if (res[1]!=0) res[1][156]=a43;
  a43=arg[4]? arg[4][157] : 0;
  if (res[1]!=0) res[1][157]=a43;
  a43=arg[4]? arg[4][158] : 0;
  if (res[1]!=0) res[1][158]=a43;
  a43=arg[4]? arg[4][159] : 0;
  if (res[1]!=0) res[1][159]=a43;
  a43=arg[4]? arg[4][160] : 0;
  if (res[1]!=0) res[1][160]=a43;
  a43=arg[4]? arg[4][161] : 0;
  if (res[1]!=0) res[1][161]=a43;
  a43=arg[4]? arg[4][162] : 0;
  if (res[1]!=0) res[1][162]=a43;
  a43=arg[4]? arg[4][163] : 0;
  if (res[1]!=0) res[1][163]=a43;
  a43=arg[4]? arg[4][164] : 0;
  if (res[1]!=0) res[1][164]=a43;
  a43=arg[4]? arg[4][165] : 0;
  a44=arg[4]? arg[4][168] : 0;
  a45=(a02*a44);
  a43=(a43+a45);
  if (res[1]!=0) res[1][165]=a43;
  a43=arg[4]? arg[4][166] : 0;
  a45=arg[4]? arg[4][169] : 0;
  a46=(a02*a45);
  a43=(a43+a46);
  if (res[1]!=0) res[1][166]=a43;
  a43=arg[4]? arg[4][167] : 0;
  a46=arg[4]? arg[4][170] : 0;
  a42=(a02*a46);
  a43=(a43+a42);
  if (res[1]!=0) res[1][167]=a43;
  if (res[1]!=0) res[1][168]=a44;
  if (res[1]!=0) res[1][169]=a45;
  if (res[1]!=0) res[1][170]=a46;
  a46=arg[4]? arg[4][171] : 0;
  if (res[1]!=0) res[1][171]=a46;
  a46=arg[4]? arg[4][172] : 0;
  if (res[1]!=0) res[1][172]=a46;
  a46=arg[4]? arg[4][173] : 0;
  if (res[1]!=0) res[1][173]=a46;
  a46=arg[4]? arg[4][174] : 0;
  if (res[1]!=0) res[1][174]=a46;
  a46=arg[4]? arg[4][175] : 0;
  if (res[1]!=0) res[1][175]=a46;
  a46=arg[4]? arg[4][176] : 0;
  if (res[1]!=0) res[1][176]=a46;
  a46=arg[4]? arg[4][177] : 0;
  if (res[1]!=0) res[1][177]=a46;
  a46=arg[4]? arg[4][178] : 0;
  if (res[1]!=0) res[1][178]=a46;
  a46=arg[4]? arg[4][179] : 0;
  if (res[1]!=0) res[1][179]=a46;
  a46=arg[4]? arg[4][180] : 0;
  a45=arg[4]? arg[4][183] : 0;
  a44=(a02*a45);
  a46=(a46+a44);
  if (res[1]!=0) res[1][180]=a46;
  a46=arg[4]? arg[4][181] : 0;
  a44=arg[4]? arg[4][184] : 0;
  a43=(a02*a44);
  a46=(a46+a43);
  if (res[1]!=0) res[1][181]=a46;
  a46=arg[4]? arg[4][182] : 0;
  a43=arg[4]? arg[4][185] : 0;
  a42=(a02*a43);
  a46=(a46+a42);
  if (res[1]!=0) res[1][182]=a46;
  if (res[1]!=0) res[1][183]=a45;
  if (res[1]!=0) res[1][184]=a44;
  if (res[1]!=0) res[1][185]=a43;
  a43=arg[4]? arg[4][186] : 0;
  if (res[1]!=0) res[1][186]=a43;
  a43=arg[4]? arg[4][187] : 0;
  if (res[1]!=0) res[1][187]=a43;
  a43=arg[4]? arg[4][188] : 0;
  if (res[1]!=0) res[1][188]=a43;
  a43=arg[4]? arg[4][189] : 0;
  if (res[1]!=0) res[1][189]=a43;
  a43=arg[4]? arg[4][190] : 0;
  if (res[1]!=0) res[1][190]=a43;
  a43=arg[4]? arg[4][191] : 0;
  if (res[1]!=0) res[1][191]=a43;
  a43=arg[4]? arg[4][192] : 0;
  if (res[1]!=0) res[1][192]=a43;
  a43=arg[4]? arg[4][193] : 0;
  if (res[1]!=0) res[1][193]=a43;
  a43=arg[4]? arg[4][194] : 0;
  if (res[1]!=0) res[1][194]=a43;
  a43=arg[4]? arg[4][195] : 0;
  a44=arg[4]? arg[4][198] : 0;
  a45=(a02*a44);
  a43=(a43+a45);
  if (res[1]!=0) res[1][195]=a43;
  a43=arg[4]? arg[4][196] : 0;
  a45=arg[4]? arg[4][199] : 0;
  a46=(a02*a45);
  a43=(a43+a46);
  if (res[1]!=0) res[1][196]=a43;
  a43=arg[4]? arg[4][197] : 0;
  a46=arg[4]? arg[4][200] : 0;
  a42=(a02*a46);
  a43=(a43+a42);
  if (res[1]!=0) res[1][197]=a43;
  if (res[1]!=0) res[1][198]=a44;
  if (res[1]!=0) res[1][199]=a45;
  if (res[1]!=0) res[1][200]=a46;
  a46=arg[4]? arg[4][201] : 0;
  if (res[1]!=0) res[1][201]=a46;
  a46=arg[4]? arg[4][202] : 0;
  if (res[1]!=0) res[1][202]=a46;
  a46=arg[4]? arg[4][203] : 0;
  if (res[1]!=0) res[1][203]=a46;
  a46=arg[4]? arg[4][204] : 0;
  if (res[1]!=0) res[1][204]=a46;
  a46=arg[4]? arg[4][205] : 0;
  if (res[1]!=0) res[1][205]=a46;
  a46=arg[4]? arg[4][206] : 0;
  if (res[1]!=0) res[1][206]=a46;
  a46=arg[4]? arg[4][207] : 0;
  if (res[1]!=0) res[1][207]=a46;
  a46=arg[4]? arg[4][208] : 0;
  if (res[1]!=0) res[1][208]=a46;
  a46=arg[4]? arg[4][209] : 0;
  if (res[1]!=0) res[1][209]=a46;
  a46=arg[4]? arg[4][210] : 0;
  a45=arg[4]? arg[4][213] : 0;
  a44=(a02*a45);
  a46=(a46+a44);
  if (res[1]!=0) res[1][210]=a46;
  a46=arg[4]? arg[4][211] : 0;
  a44=arg[4]? arg[4][214] : 0;
  a43=(a02*a44);
  a46=(a46+a43);
  if (res[1]!=0) res[1][211]=a46;
  a46=arg[4]? arg[4][212] : 0;
  a43=arg[4]? arg[4][215] : 0;
  a02=(a02*a43);
  a46=(a46+a02);
  if (res[1]!=0) res[1][212]=a46;
  if (res[1]!=0) res[1][213]=a45;
  if (res[1]!=0) res[1][214]=a44;
  if (res[1]!=0) res[1][215]=a43;
  a43=arg[4]? arg[4][216] : 0;
  if (res[1]!=0) res[1][216]=a43;
  a43=arg[4]? arg[4][217] : 0;
  if (res[1]!=0) res[1][217]=a43;
  a43=arg[4]? arg[4][218] : 0;
  if (res[1]!=0) res[1][218]=a43;
  a43=arg[4]? arg[4][219] : 0;
  if (res[1]!=0) res[1][219]=a43;
  a43=arg[4]? arg[4][220] : 0;
  if (res[1]!=0) res[1][220]=a43;
  a43=arg[4]? arg[4][221] : 0;
  if (res[1]!=0) res[1][221]=a43;
  a43=arg[4]? arg[4][222] : 0;
  if (res[1]!=0) res[1][222]=a43;
  a43=arg[4]? arg[4][223] : 0;
  if (res[1]!=0) res[1][223]=a43;
  a43=arg[4]? arg[4][224] : 0;
  if (res[1]!=0) res[1][224]=a43;
  return 0;
}

CASADI_SYMBOL_EXPORT int predict_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int predict_function_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int predict_function_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void predict_function_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int predict_function_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void predict_function_release(int mem) {
}

CASADI_SYMBOL_EXPORT void predict_function_incref(void) {
}

CASADI_SYMBOL_EXPORT void predict_function_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int predict_function_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int predict_function_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real predict_function_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* predict_function_name_in(casadi_int i) {
  switch (i) {
    case 0: return "X";
    case 1: return "U";
    case 2: return "W";
    case 3: return "dt";
    case 4: return "P";
    case 5: return "Q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* predict_function_name_out(casadi_int i) {
  switch (i) {
    case 0: return "X_pred";
    case 1: return "P_pred";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* predict_function_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* predict_function_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int predict_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int predict_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
